apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vulcano
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/mauriciofsnts/vulcano
    targetRevision: HEAD
    path: .infra/manifests/vulcano
  destination:
    server: https://kubernetes.default.svc
    namespace: vulcano
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
