name: vulcano

repos:
  - name: dbcafe-base
    url: https://code.db.cafe/api/packages/dbcafe/helm

installs:
  - name: vulcano
    chart: dbcafe-base/public-app

  - name: valkey
    chart: oci://registry-1.docker.io/bitnamicharts/valkey
    chartVersion: '2.3.0'

envs:
  - name: master
    namespace: vulcano
    for:
      branch: master
    values:
      - prd.yaml
