apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: vulcano

resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml

images:
  - name: ghcr.io/mauriciofsnts/vulcano
    newTag: a0c842c
