# Server Configuration
server:
  port: ":8080"  # Port the server will listen on (e.g., ":8080", ":3000")

# Database Configuration
db:
  type: "postgres" # Database type: "postgres" or "sqlite"

  # Postgres Configuration (used if type: postgres)
  postgres:
    host: "localhost"
    port: 5432
    user: "postgres"
    password: "password"
    database: "mydb"

  # SQLite Configuration (used if type: sqlite)
  sqlite:
    path: "./mydb.db"

  migrate: true  # Run database migrations on startup (true/false)

# Logging Configuration
log:
  level: "INFO"       # Log level: "DEBUG", "INFO", "WARN", "ERROR"
  type: "text"        # Log format: "text", "json", "colored"
  showSource: true    # Show log source (file and line) (true/false)

# Discord Configuration
discord:
  token: "YOUR_DISCORD_BOT_TOKEN"
  prefix: "!"           # Prefix for bot commands
  guildID: "YOUR_GUILD_ID"
  syncCommands: true    # Sync bot commands with Discord on startup (true/false)

# URL Shortener Configuration
shortener:
  endpoint: "https://your-shortener-api.com"
  apiKey: "YOUR_SHORTENER_API_KEY"

# News API Configuration
news:
  newsapi_apikey: "YOUR_NEWSAPI_API_KEY"

# Football Data API Configuration
footballData:
  apiKey: "YOUR_FOOTBALL_DATA_API_KEY"
