db:
  host: localhost
  port: 5432
  user: postgres
  password: password
  database: my_database

# The possible log levels are: DEBUG, INFO and ERROR
loglevel: DEBUG

# Discord bot configuration
discord:
  token: "your_token_here"
  prefix: "!"
  guildId: "your_guild_id_here"
  syncCommands: false

# shortener configuration
shortener:
  endpoint: "https://url.db.cafe/api/v1/links"
  apiKey: "your_api_key_here"
