server:
  port: 8080

db:
  type: 'sqlite'
  migrate: true
  # postgres:
  #   host: 'localhost'
  #   port: 5432
  #   user: 'admin'
  #   password: 'admin'
  #   dbname: 'test'
  sqlite:
    path: './db.sqlite'

# The possible log levels are: DEBUG, INFO and ERROR
loglevel: DEBUG

# Discord bot configuration
discord:
  token: "your_token_here"
  prefix: "!"
  guildId: "your_guild_id_here"
  syncCommands: false

# shortener configuration
shortener:
  endpoint: "https://url.db.cafe/api/v1/links"
  apiKey: "your_api_key_here"

news:
  newsapi_apikey: "your_newsapi_api_key_here"

footballData:
  apiKey: "your_football_data_api_key_here"
