name: Deploy
run-name: Deploy 🚀
on:
  push:
    branches:
      - master

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Docker Context for Buildx
        id: buildx-context
        run: |
          docker context create builders

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
        with:
          version: latest
          endpoint: builders

      - name: "Login to GitHub Container Registry"
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}

      - name: Set short git commit SHA
        id: vars
        run: |
          echo "COMMIT_SHORT_SHA=$(git rev-parse --short ${{ github.sha }})" >> $GITHUB_ENV

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          file: Dockerfile
          context: .
          push: true
          tags: ghcr.io/mauriciofsnts/vulcano:${{ env.COMMIT_SHORT_SHA }},ghcr.io/mauriciofsnts/vulcano:${{ github.ref_name }}

      - name: Upgrade install
        uses: pauloo27/k7z-upgrade@v1.1.0
        with:
          base_url: https://k7z.mrzt.dev/api/v0
          team_name: main
          project_name: vulcano
          api_key: ${{ secrets.K7Z_SECRET }}
          ref: ${{ github.ref_name }}
          data: |
            {
              "tag": "${{ env.COMMIT_SHORT_SHA }}"
            }
